apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "application.fullname" . }}-config"
  labels:
{{ include "application.labels" . | indent 4 }}
data:
{{ include "application.config" . | trim | indent 2 }}
