{{- if .Values.persistentVolume.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application.fullname" . }}-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  resources:
    requests:
      storage: 20Gi
{{- end }}